site_name: CLI client for PANDA | Drift platform
site_description: CLI client for PANDA | Drift platform
docs_dir: .
nav:
  - Home:
      - README.md
  - CLI Reference: docs/cli.md
  - Usage:
      - docs/aliases.md

repo_name: panda-official/DriftCLI
repo_url: https://github.com/panda-official/DriftCLI
edit_uri: edit/develop/


# Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
  logo: docs/img/favicon.png
  favicon: docs/img/favicon.png
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - plantuml_markdown:
      format: svg
  - mkdocs-click


plugins:
  - same-dir

extra:
  analytics:
    provider: google
    property: G-KVT7VSNVGC
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
